Repository wafflestudio/19.5-rookies, pull requests merged in 2021-08, with the labels that each got.

#19 우현민 android 신청합니다
  seminar-list.md
Labels: Android

#42 김연정 backend 신청합니다
  seminar-list.md
Labels: Django

#44 황승준 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#45 김동현 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#46 최하늘 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#47 설한동 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#48 권민규 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#49 고현준 android 세미나 신청합니다
  seminar-list.md
Labels: Android

#51 안중원 react 세미나 신청합니다
  seminar-list.md
Labels: React

#178 조성민 react 세미나 신청합니다
  seminar-list.md
Labels: React

#176 박영서 react 세미나 신청합니다
  seminar-list.md
Labels: React

#177 엄의섭 ios 세미나 신청합니다
  seminar-list.md
Labels: iOS

#174 이채민 iOS 세미나 신청합니다
  seminar-list.md
Labels: iOS

#169 박지연 react 세미나 신청합니다
  seminar-list.md
Labels: React

#168 최주빈 iOS 세미나 신청합니다
  seminar-list.md
Labels: iOS

#167 최성준 android 신청합니다
  seminar-list.md
Labels: Android

#166 오인규 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#164 양주현 backend 신청합니다
  seminar-list.md
Labels: Django

#165 서지민 react 신청합니다.
  seminar-list.md
Labels: React

#163 이대희 react 신청합니다
  seminar-list.md
Labels: React

#159 김우성 iOS 세미나 신청합니다
  seminar-list.md
Labels: iOS

#158 김수영 backend 세미나 신청합니다.
  seminar-list.md
Labels: Django

#157 이하동 react 세미나 신청합니다
  seminar-list.md
Labels: React

#156 유하은 android 세미나 신청합니다
  seminar-list.md
Labels: Android

#155 이성민 React 신청합니다
  seminar-list.md
Labels: React

#154 박민우 iOS 신청합니다
  seminar-list.md
Labels: iOS

#153 이지현 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#152 조용찬 react 세미나 신청합니다.
  seminar-list.md
Labels: React

#150 박형철 iOS 신청합니다
  seminar-list.md
Labels: iOS

#146 최민우 android 세미나 신청합니다
  seminar-list.md
Labels: Android

#145 서민균 react 신청합니다.
  seminar-list.md
Labels: React

#144 박윤아 backend 신청합니다
  seminar-list.md
Labels: Django

#143 김준희 android 세미나 신청합니다
  seminar-list.md
Labels: Android

#142 최수완 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#141 전현성 backend seminar 신청합니다
  seminar-list.md
Labels: Django

#140 이종현 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#139 임채은 react 세미나 신청합니다
  seminar-list.md
Labels: React

#138 권재영 backend 신청합니다
  seminar-list.md
Labels: Django

#137 김범수 iOS 신청합니다
  seminar-list.md
Labels: iOS

#136 전형민 backend 신청합니다
  seminar-list.md
Labels: Django

#135 조형근 react 신청합니다
  seminar-list.md
Labels: React

#133 오민혁 react 신청합니다
  seminar-list.md
Labels: React

#132 정다은 android 세미나 신청합니다
  seminar-list.md
Labels: Android

#131 조성민 android 신청합니다
  seminar-list.md
Labels: Android

#130 김한곤 backend 신청합니다.
  seminar-list.md
Labels: Django

#129 김소원 android 세미나 신청합니다
  seminar-list.md
Labels: Android

#128 김정훈 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#126 이민재 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#125 한창희 backend 신청합니다
  seminar-list.md
Labels: Django

#124 김수연 android 신청합니다.
  seminar-list.md
Labels: Android

#123 이재현 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#122 고수창 android 세미나 신청합니다
  seminar-list.md
Labels: Android

#121 김남태 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#120 조강현 backend 세미나 신청합니다.
  seminar-list.md
Labels: Django

#119 오태양 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#118 이유나 iOS 세미나 신청합니다
  seminar-list.md
Labels: iOS

#117 김지현 backend 신청합니다.
  seminar-list.md
Labels: Django

#116 최병욱 backend 신청합니다
  seminar-list.md
Labels: Django

#115 강지호 backend 신청합니다
  seminar-list.md
Labels: Django

#114 이소현 react 세미나 신청합니다
  seminar-list.md
Labels: React

#112 홍순범 backend 신청합니다
  seminar-list.md
Labels: Django

#111 권민정 backend 신청합니다
  seminar-list.md
Labels: Django

#110 한동엽 react 세미나 신청합니다
  seminar-list.md
Labels: React

#109 정성태 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#108 고현수 backend 신청합니다
  seminar-list.md
Labels: Django

#107 윤상면 react 신청합니다
  seminar-list.md
Labels: React

#106 박준영 backend 신청합니다
  seminar-list.md
Labels: Django

#105 박신홍 iOS 세미나 신청합니다.
  seminar-list.md
Labels: iOS

#101 안민규 react 세미나 신청합니다
  seminar-list.md
Labels: React

#100 박현수 backend 신청합니다
  seminar-list.md
Labels: Django

#99 김의기 react 세미나 신청합니다
  seminar-list.md
Labels: React

#98 김진수 android 세미나 신청합니다.
  seminar-list.md
Labels: Android

#97 김지완 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#96 문보현 backend 세미나 신청합니다.
  seminar-list.md
Labels: Django

#95 한동호 android 세미나 신청합니다
  seminar-list.md
Labels: Android

#94 배수민 backend 신청합니다
  seminar-list.md
Labels: Django

#92 이민준 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#90 최준우 backend 세미나 신청합니다.
  seminar-list.md
Labels: Django

#91 정재영 android 신청합니다
  seminar-list.md
Labels: Android

#89 박진영 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#88 김민서 react 세미나 신청합니다
  seminar-list.md
Labels: React

#87 윤창민 backend 신청합니다
  seminar-list.md
Labels: Django

#86 오형택 react 신청합니다
  seminar-list.md
Labels: React

#85 이두현 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#84 류영상 react 신청합니다
  seminar-list.md
Labels: React

#83 박준영 react 세미나 신청합니다
  seminar-list.md
Labels: React

#81 김형윤 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#80 오이석 backend 세미나 신청합니다.
  seminar-list.md
Labels: Django

#79 고동현 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#76 강성복 backend 신청합니다
  seminar-list.md
Labels: Django

#72 민준기 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#78 박정훈 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#77 권신영 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#75 김민석 react 신청합니다
  seminar-list.md
Labels: React

#74 이철민 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#73 박재완 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#71 홍정현 android 세미나 신청합니다
  seminar-list.md
Labels: Android

#70 손융 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#69 최유림 iOS 세미나 신청합니다
  seminar-list.md
Labels: iOS

#68 전진용 backend 신청합니다
  seminar-list.md
Labels: Django

#67 고계훈 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#66 안재우 iOS 세미나 신청합니다.
  seminar-list.md
Labels: iOS

#65 문용균 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#64 이나경 react 세미나 신청합니다
  seminar-list.md
Labels: React

#63 이서영 backend 신청합니다
  seminar-list.md
Labels: Django

#62 이경현 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#60 신동섭 Backend 세미나 신청합니다.
  seminar-list.md
Labels: Django

#59 김혜민 react 세미나 신청합니다
  seminar-list.md
Labels: React

#58 김영인 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#57 신우철 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#56 이준경 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#55 red1108 백엔드 신청합니다
  seminar-list.md
Labels: Django

#54 이정후 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#53 이민규 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#52 유가현 backend 신청합니다
  seminar-list.md
Labels: Django

#50 김시연 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#102 이승원 react 세미나 신청합니다
  seminar-list.md
Labels: React

#182 이해원 android 세미나 신청합니다
  seminar-list.md
Labels: Android

#183 고현준 android 신청합니다
  seminar-list.md
Labels: Android

#43 정윤재 backend 신청합니다
  seminar-list.md
Labels: Django

#185 이승엽 react 신청합니다.
  seminar-list.md
Labels: React

#186 박재완 backend 세미나 신청합니다
  seminar-list.md
Labels: Django

#187 이재민 react 신청합니다
  seminar-list.md
Labels: React

#188 오형택 android 청강 신청합니다
  seminar-list.md
Labels: Android

#161 이승현 React 신청합니다
  seminar-list.md
Labels: React

#189 이승호 backend 신청합니다
  seminar-list.md
Labels: Django

#190 김경민 react 신청합니다.
  seminar-list.md
Labels: React

#194 양주현 android 신청합니다(수정)
  seminar-list.md
Labels: Android

#195 김창아 react 신청합니다
  seminar-list.md
Labels: React

#61 최유진 iOS 세미나 신청합니다
  seminar-list.md
Labels: iOS

#197 홍용기 react 신청합니다.
  seminar-list.md
Labels: React

#198 최유진 iOS 세미나 신청합니다
  seminar-list.md
Labels: iOS

#199 이정민 백엔드 신청합니다(수정)
  seminar-list.md
Labels: Django

#201 박기현 backend 지원합니다
  seminar-list.md
Labels: Django

#103 김영범 backend 세미나 신청합니다
  seminar-list.md
Labels: Django
